#!/usr/bin/env ruby
# frozen_string_literal: true

require "w3c_validators"

def validate(file)
  puts "Checking #{file}..."

  path = File.expand_path "../_site/#{file}", __dir__
  results = W3CValidators::NuValidator.new.validate_file(path)

  return puts "Valid!" if results.errors.empty?

  results.errors.each { |err| puts err }
  exit 1
end

validate "index.html"
